# Generated by Django 5.1.15 on 2026-04-02 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0003_customuser_phone_number_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('serviteur', 'Serviteur')], default='serviteur', max_length=10),
        ),
        migrations.CreateModel(
            name='ServiteurFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, help_text='Pourcentage /100')),
                ('statut', models.IntegerField(choices=[(0, 'Échoué'), (1, 'Validé')], default=0)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traning.formation')),
                ('serviteur', models.ForeignKey(limit_choices_to={'role': 'serviteur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('serviteur', 'formation')},
            },
        ),
        migrations.DeleteModel(
            name='StudentFormation',
        ),
    ]
