# Generated by Django 5.1.6 on 2026-04-06 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0004_alter_customuser_role_serviteurformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiteurVertumetre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Réponses')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('serviteur', models.OneToOneField(limit_choices_to={'role': 'serviteur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Serviteur')),
            ],
            options={
                'verbose_name': 'Vertumètre Serviteur',
                'verbose_name_plural': 'Vertumètres Serviteurs',
            },
        ),
    ]
