# Generated by Django 5.1.15 on 2026-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0005_serviteurvertumetre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviteurformation',
            name='statut',
            field=models.IntegerField(choices=[(0, 'Échoué'), (1, 'Validé'), (2, 'En cours')], default=2),
        ),
    ]
