# Generated by Django 5.1.15 on 2026-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0006_add_en_cours_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviteurformation',
            old_name='date_fin',
            new_name='date_limite',
        ),
        migrations.AddField(
            model_name='serviteurformation',
            name='date_soumission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
