# Generated by Django 5.1.15 on 2026-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0008_add_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviteurvertumetre',
            name='submissions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de soumissions'),
        ),
    ]
