# Generated by Django 5.1.15 on 2026-07-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0009_serviteurvertumetre_submissions_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Département')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviteurs', to='traning.departement', verbose_name='Département'),
        ),
    ]
