# Generated by Django 4.2.24 on 2026-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traning', '0010_departement_customuser_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='questionnaire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise à disposition (HTML)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='questionnaire_html',
            field=models.TextField(blank=True, default='', help_text="Contenu HTML d'un questionnaire importé. Prend le pas sur le questionnaire JSON lorsqu'il est renseigné.", verbose_name='Questionnaire (HTML)'),
        ),
        migrations.AddField(
            model_name='serviteurformation',
            name='html_responses',
            field=models.JSONField(blank=True, null=True, verbose_name='Réponses du questionnaire HTML'),
        ),
    ]
